s-tip/stip-rs

- src/ctirs/core/mongo/documents_stix.py
> Fix to correct a stix-slide issue

- src/ctirs/core/adapter/misp/upload/control.py
Sorry.
I found also that S-TIP can not connect to misp via proxy.
I fixed it.
> fixed that S-TIP can not connect to misp via proxy

- src/ctirs/models/sns/feeds/models.py
Corespond to s-tip/stip-sns#17.
> I fixed an encoding issue

- src/ctirs/api/v1/sns/views.py
Correspond to s-tip/stip-sns#19.
> Fixed to unload next 10 latest  posts correctly.

- src/ctirs/configuration/user/templates/change_pwd.html
- src/ctirs/configuration/user/templates/user.html
- src/ctirs/configuration/user/urls.py
- src/ctirs/configuration/user/views.py
- src/static/ctirs/js/change_pwd.js
- src/static/ctirs/js/user_configuration.js
If a S-TIP user forget own password, S-TIP could not modify the password.
So I add a function which a S-TIP admin user can modify any other user password.
> Add a modified password function

- src/ctirs/configuration/user/views.py
A S-TIP user force jump to a change password screen when the user login after an admin role user modified the user password.
> Force jump to change password screen.

- src/ctirs/core/stix/regist.py
- src/ctirs/core/taxii/taxii.py
If  S-TIP TAXII client uses an authorization based on crt/key files, an error occurred.
I fixed this issue.
> Fixed an authorization error via cert auth.

- src/ctirs/api/v1/sns/views.py
- src/ctirs/models/sns/feeds/models.py
- src/ctirs/models/sns/feeds/rs.py
対応issue https://github.com/s-tip/stip-sns/issues/31
<修正内容>
- 検索ワードに一致するSTIXの情報を返却できるように修正
> Modify search result screen

- src/ctirs/api/__init__.py
- src/ctirs/api/v1/package_id/views.py
- src/ctirs/core/mongo/documents_stix.py
- src/ctirs/core/stix/regist.py
- src/ctirs/list/ajax/views.py
- src/ctirs/list/views.py
- src/ctirs/models/sns/feeds/models.py
When you click the x button, the action disappears.
However, reloading the feeds screen will restore them.
There is some cache left.
https://github.com/s-tip/stip-sns/issues/33
> Fix allow users to delete their comments posted on SNS

- src/ctirs/configuration/user/ajax/urls.py
- src/ctirs/configuration/user/ajax/views.py
- src/ctirs/configuration/user/templates/user.html
- src/static/ctirs/js/user_configuration.js
This pull request is generated from the issue #70 .
This is a follow on response from the pull request #68 .
> Fixed the names of user configuration endpoints.

- src/ctirs/adapter/isight/detail/views.py
- src/ctirs/adapter/isight/views.py
- src/ctirs/adapter/misp/detail/views.py
- src/ctirs/adapter/misp/views.py
- src/ctirs/adapter/otx/detail/views.py
- src/ctirs/adapter/otx/views.py
- src/ctirs/api/v1/stix_files/views.py
- src/ctirs/api/v1/stix_files_v2/views.py
- src/ctirs/configuration/mongo/views.py
- src/ctirs/configuration/system/views.py
- src/ctirs/configuration/taxii_client/detail/views.py
- src/ctirs/configuration/taxii_client/views.py
- src/ctirs/configuration/taxii_server/detail/views.py
- src/ctirs/configuration/taxii_server/views.py
- src/ctirs/configuration/user/ajax/views.py
- src/ctirs/configuration/user/views.py
- src/ctirs/core/common.py
- src/ctirs/dashboard/urls.py
- src/ctirs/list/views.py
- src/ctirs/login/views.py
- src/ctirs/poll/views.py
- src/ctirs/profile/views.py
- src/ctirs/upload/views.py
> Three duplicated functions should be moved to stip-common.

- src/ctirs/list/urls.py
- src/ctirs/list/views.py
Changed to the process of redirect so that the ID does not remain in the URL.
> Changed to process to redirect. (for #76 issue)

- src/ctirs/adapter/isight/templates/isight.html
- src/ctirs/adapter/misp/templates/misp.html
- src/ctirs/adapter/otx/templates/otx.html
- src/ctirs/api/v1/stix_files_v2/views.py
- src/ctirs/core/adapter/__init__.py
- src/ctirs/core/adapter/otx/otx.py
- src/ctirs/poll/templates/poll_detail.html
- src/static/ctirs/js/adapter_isight.js
- src/static/ctirs/js/adapter_misp.js
- src/static/ctirs/js/adapter_otx.js
- src/static/ctirs/js/poll_detail.js
Fixed an issue about #84 (Cannot poll from AlienVault OTX)  and #85 (Popover herlp window for timeformat).
> Alienvault OTX - Successful Run but no returned stix files #54  and support a popup help window.

- bin/setup_env.py
- src/ctirs/settings.py
> Fixed issues about SECRET_KEYS and TIME_ZONE.

- src/ctirs/core/mongo/documents_stix.py
> Create A Tags Collection in Mongo Database #93

- src/ctirs/api/v1/sns/views.py
- src/ctirs/core/mongo/documents_stix.py
This is a pull request for #97.
> Added search criteria for Tags.

- src/ctirs/api/__init__.py
- src/ctirs/api/v1/sns/urls.py
- src/ctirs/api/v1/sns/views.py
> When a user input hashtags in a search field, S-TIP recommends hashtags.

- src/ctirs/api/v1/gv/views.py
- src/ctirs/core/mongo/documents_stix.py
Display hashtag nodes and links and search exact match nodes.
This pull request is correspond with s-tip/stip-gv#44.
> Display hashtag nodes and links and search exact match nodes

- src/ctirs/api/v1/sns/views.py
> Fixed to separate search words with double-byte spaces. 

- src/ctirs/api/v1/sns/views.py
> Not suggested for the second and subsequent Hashtags in the search word

- src/ctirs/core/adapter/misp/upload/control.py
> Fix to connect to a MISP intsance whose url contains port number

- src/ctirs/settings.py
Issue about s-tip/stip-common#84.
> Fixed an issue about SSO

- src/ctirs/api/v1/stix_files_v2/urls.py
- src/ctirs/api/v1/stix_files_v2/views.py
For Issue #113.
- Delete a STIX package by object_id.
- Return a STIX package list by object_id
> Add some REST API functions.

- src/ctirs/migrations/0022_auto_20190228_2217.py
- src/ctirs/migrations/0036_auto_20191213_1145.py
- src/ctirs/models/sns/config/fixture/sns_config.json
- src/ctirs/models/sns/config/models.py
> Replace example values

- src/ctirs/configuration/taxii_server/detail/templates/configuration_taxii_server_detail.html
- src/ctirs/configuration/taxii_server/detail/views.py
- src/ctirs/core/mongo/documents.py
- src/static/ctirs/js/configuration_taxii_server_detail.js
Issue about #128  .
I modified `stip-rs` to enable to return STIX Files by the `community` instead of `information sources` when a TAXII client poll to S-TIP TAXII 1.1 Server.
> Enable to specify the TAXII 1.1 Server Poll STIX Files via Community.

- src/ctirs/models/sns/feeds/models.py
Issue about #130 .
Ignore the STIX format error with a certain case.
> Ignore a STIX format error.

- src/ctirs/core/taxii/taxii.py
- src/ctirs/core/taxii/taxii11.py
- src/ctirs/core/taxii/taxii20.py
About the issue #138 .
Display an error message about TAXII client poll.
> S-TIP displays an error message when TAXII client fails to poll.

- src/ctirs/core/mongo/documents_stix.py
> For the latest stix2-elevator lib.

- src/ctirs/core/mongo/documents_stix.py
- src/ctirs/models/sns/feeds/models.py
Issue about #146 and #147 .
- Skip to create unnecessary cache objects
- Fix to undelete StixFile from the RS list
> Fixed some issues

- src/ctirs/settings.py
Fixed an issue about s-tip/stip-common#103
> Add a secure flag on csrf
